# Generated by Django 3.1.7 on 2021-02-24 18:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_usage_calc_mode', models.CharField(choices=[('MPG', 'Miles per gallon'), ('LP100KM', 'Litres per 100 km'), ('KPG', 'Kilometers per gallon'), ('GP100KM', 'Gallons per 100 km')], default='LP100KM', max_length=7)),
                ('distance_unit', models.CharField(choices=[('KM', 'kilometers'), ('MI', 'miles')], default='KM', max_length=2)),
                ('fuel_quantity_unit', models.CharField(choices=[('LTR', 'litres'), ('GAL', 'gallons')], default='LTR', max_length=3)),
                ('name', models.CharField(max_length=200)),
                ('licence_plate', models.CharField(max_length=20)),
                ('initial_odometer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('amount_filled', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tank_full', models.BooleanField(default=True)),
                ('fill_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuelmanager.car')),
            ],
        ),
    ]
