# Generated by Django 3.1.7 on 2021-02-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuelmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='licence_plate',
            new_name='license_plate',
        ),
    ]
