# Generated by Django 3.1.7 on 2021-02-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuelmanager', '0002_auto_20210225_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='initial_odometer',
        ),
    ]
