# Generated by Django 3.1.7 on 2021-03-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuelmanager', '0004_auto_20210301_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Department',
        ),
    ]
