# Generated by Django 3.1.7 on 2021-03-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuelmanager', '0005_auto_20210301_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='company',
            new_name='department',
        ),
    ]
